### ISSUE TITLE
Editor Overscroll from Xcode

### ISSUE THREAD

**Issue by iankoex** [CodeEditApp/CodeEditTextView#97] opened 2022-11-22 17:52 UTC
In Xcode there is the ability to set Editor Overscroll as shown in the screenshot below. Having this would be helpful.

 
![Xcode screenshot](https://user-images.githubusercontent.com/30172987/203385754-83b0cd75-752b-41ae-90bc-c6544b72b624.png)

**Comment by lukepistrol** [comment] 2022-11-22 17:58
duplicate of #63

**Closed** 2022-11-22 18:00 UTC
Labels: duplicate, enhancement
