### ISSUE TITLE
✨ Matching Tag/Bracket Highlighting

### ISSUE THREAD

**Issue by austincondiff** [CodeEditApp/CodeEditTextView#67] opened 2022-10-01 05:30 UTC
When the cursor moves to a bracket, the matching bracket temporarily highlights to show the user the opposite bracket.

https://user-images.githubusercontent.com/806104/193524210-a7d6b4f4-9a67-4ad8-9f66-49191eefd5cc.mov

**Comment by thecoolwinter** [comment] 2022-10-02 01:52
Duplicate of #39, adding the hacktoberfest tag there.

**Comment by austincondiff** [comment] 2022-10-02 18:52
I'll add an issue description soon

**Closed** 2023-05-08 20:17 UTC
Labels: enhancement
