### ISSUE TITLE
🐞 Line height decreases when no characters exist on line

### ISSUE THREAD

**Issue by 0xWDG** [CodeEditApp/CodeEditTextView#20] opened 2022-06-11 13:53 UTC
### Description

The line height decreases if no characters exist on the line.

- With no text
  <img width="217" alt="image" src="https://user-images.githubusercontent.com/1290461/173190517-6e0b03a7-2211-455c-87a4-71bbc634d82b.png">
- With text
  <img width="215" alt="image" src="https://user-images.githubusercontent.com/1290461/173190559-74d456ec-25f5-4e30-8492-c5f6a36df2e5.png">

### Related issues
- #152
- #151

**Comment by lukepistrol** [comment] 2023-01-18 17:19
@ben-p-commits assigned it to you

**Comment by ben-p-commits** [comment] 2023-01-18 17:42
After doing some digging, I do [see a code path for handling the empty text container case](https://github.com/krzyzanowskim/STTextView/blob/95bd21f8d1507b1215ce462391df22436bf3223a/Sources/STTextView/STLineNumberRulerView.swift#L104) when laying out the `STLineNumberRulerView` in [STTextView](https://github.com/krzyzanowskim/STTextView)

<img width="1175" alt="image" src="https://user-images.githubusercontent.com/5067237/213255188-5e5dc256-d104-4eaa-a353-9ca6ce96b964.png">

I'm not seeing this bug in the sample app embedded in the dependency... a good sign we can fix this on our end.

**Comment by ben-p-commits** [comment] 2023-01-18 17:57
Also confirmed that pulling in the latest `main` branch work on STTextView doesn't address this.

**Comment by austincondiff** [comment] 2023-02-16 23:22
@ben-p-commits I believe the problem was caused when I decreased the font size of the line numbers. Because there is no text, the line collapses on the tallest item which is the smaller line number after removing the last character of the larger code. We may need a minimum height on each line or set the line height of the line number to be equal to the line height of the code.

**Comment by luah5** [comment] 2023-03-29 12:40
a slight edit to #170 could fix this issue.

**Comment by austincondiff** [comment] 2023-03-29 13:55
@luah5 Did you want to take this one then?

**Comment by luah5** [comment] 2023-03-29 13:56
> @luah5 Did you want to take this one then?

i've barely looked into this but i'll take it.

**Comment by luah5** [comment] 2023-04-25 19:48
This ***might*** have something to do with @Eliulm's [message](https://discord.com/channels/951544472238444645/987416899816149024/1094587447624613908) where he pointed out that the line height overlaps a bit.

**Comment by thecoolwinter** [comment] 2023-12-09 21:09
This has been resolved with #211.

https://github.com/CodeEditApp/CodeEditTextView/assets/35942988/10f8b973-ae81-4cdb-82bc-2337ee9e1176

**Closed by thecoolwinter** 2023-12-09 21:09 UTC
Labels: bug
