### ISSUE TITLE
🐞 Highlighting slowly disappears as user scrolls down

### ISSUE THREAD

**Issue by nomilious** [CodeEditApp/CodeEditTextView#109] opened 2023-01-09 10:22 UTC
### Description

CodeEdit app isn't highlighting all lines of code. It's highlighting about 85% of lines displayed in the window. To fix this I need to scroll down all the file.(after scrolling all file the highlighting remains). 

BUT: there is a scenario when scrolling doesn't help: if last few lines of file are not empty, then the'll not be highlighted. To fix this I need to add some empty lines at the end of file.

### To Reproduce

1. Open a file with an implemented highlighting(i.e .py file). The file must be longer than the CodeEdit app height.

### Expected behavior

All the file is highlighted 

### Version information

CodeEdit: [e.g. 1.0 (1)]
macOS: [e.g. 13.1.0]
Xcode: [e.g. 14.2]

**Comment by thecoolwinter** [comment] 2023-02-14 21:21
Is this still an issue with the most up to date build? I can't reproduce this.

**Comment by nomilious** [comment] 2023-02-16 05:53
Yes, it's. Issue is in the first img:
![issue](https://user-images.githubusercontent.com/83181216/219279723-aebf5a86-721d-47f2-b57e-63feaa695ca0.jpg)
![issue__2](https://user-images.githubusercontent.com/83181216/219279902-347c48bd-508b-4d65-815f-46af77b715c3.jpg)

**Version information**

CodeEdit:  0.0.1-alpha (25)
macOS: 13.1.2
Xcode: 14.2

**Comment by austincondiff** [comment] 2023-02-17 17:45
This should be fixed in the next release. If it is not please comment/reopen.

**Closed by austincondiff** 2023-02-17 17:45 UTC
Labels: bug
